### ISSUE TITLE
django 1.4

### ISSUE THREAD

**Issue by bhaugen** [sontek-archive/django-tekextensions#1]
I got your very nice component working on django 1.4.  Did not fork it and send a pull request, sorry, because I am customizing it a bunch for a project, and you did not seem to be supporting it anymore anyway.

But it's here, if you want to grab any code:
https://github.com/bhaugen/valuenetwork/tree/master/valuenetwork/tekextensions

If you want to keep supporting the component, I'll remove the customizations and do a proper fork-and-pull-request. 

Regardless, thanks, so far it's working well for me.

**Comment by sontek** [comment]
Yeah, I don't do much with django these days. Thanks for keeping it going though!
